#!/usr/bin/expect -f
set schema [lindex $argv 0]
set passwd [lindex $argv 1]

set timeout -1
spawn sudo ssh -D 22 bdna@192.168.9.103
expect {
       "(yes/no)?" {send "yes\r";exp_continue}
       "*password:" {send "bdna\r" }
}
expect "\\$"
send "sh bdna.sh\r"
expect "\>"
send "impcoll -n bdnacs201708 -d \"bdnacs for 201708\" /home/bdna/automation/installer/canton201708.bdnacs\r"
send "mkinv -m USER bdnainv201708  \"inventory for bdnacs201708\"\r"
expect "\>"
send "addcolltoinv bdnacs201708 bdnainv201708\r"
expect "Continue (y/n)*"
send "y\r"
expect "\>"
send "snapshot -f -y -a\r"
expect "\>"
send "refreshpub -y -a\r"
expect "\>"
send "refreshanalytics -y -a\r"
expect "\>"
send "exit\r"
expect "\\$"

interact
